[project]
name = "file-cleaner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
python = ">=3.12.9"
dependencies = []

[tool.poetry]
name = "file-cleaner"
version = "0.1.0"
...

[tool.poetry.packages]
include = "file_cleaner"
